#!/usr/bin/env bash
#
# Pre-Edit Hook for ROSA Trusted Actions Server
# Prevents editing generated files, vendored code, and high-risk files without warning
#
# Usage: Called automatically by Claude Code before file edits
#

set -euo pipefail

FILE="${1:-}"

if [[ -z "$FILE" ]]; then
  echo "Usage: $0 <file-path>"
  exit 1
fi

# Normalize file path to be repo-relative for consistent pattern matching
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || echo ".")
if [[ "$FILE" = /* ]]; then
  FILE="${FILE#"$REPO_ROOT"/}"
fi
# Strip leading ./
FILE="${FILE#./}"

# Helper function for interactive confirmation
confirm_or_exit() {
  local prompt="$1"
  echo "$prompt"

  if [[ ! -t 0 ]]; then
    echo "ERROR: Non-interactive environment detected"
    echo "   This operation requires manual confirmation"
    exit 1
  fi

  read -r response
  if [[ ! "$response" =~ ^[Yy]$ ]]; then
    exit 1
  fi
}

# =============================================================================
# GENERATED FILES - BLOCK EDITS
# =============================================================================

# Check for generated OpenAPI code
if [[ "$FILE" == internal/openapi/* ]]; then
  echo "BLOCKED: Cannot edit generated file: $FILE"
  echo "   This file is auto-generated by oapi-codegen."
  echo "   To regenerate: make generate"
  exit 1
fi

# =============================================================================
# LOCKFILES - WARNING
# =============================================================================

if [[ "$FILE" == "go.sum" ]]; then
  echo "WARNING: Editing go.sum directly"
  echo "   This file is managed by 'go mod tidy'."
  confirm_or_exit "   Are you sure you want to edit it manually? (y/N)"
fi

if [[ "$FILE" == "package-lock.json" ]]; then
  echo "WARNING: Editing package-lock.json directly"
  echo "   This file is managed by 'npm install'."
  confirm_or_exit "   Are you sure you want to edit it manually? (y/N)"
fi

# =============================================================================
# VENDORED CODE - BLOCK EDITS
# =============================================================================

if [[ "$FILE" == vendor/* ]]; then
  echo "BLOCKED: Cannot edit vendored code: $FILE"
  echo "   Vendor directory is managed by go modules."
  echo "   Update dependencies in go.mod instead."
  exit 1
fi

if [[ "$FILE" == node_modules/* ]]; then
  echo "BLOCKED: Cannot edit node_modules: $FILE"
  echo "   Node modules are managed by npm."
  echo "   Update dependencies in package.json instead."
  exit 1
fi

# =============================================================================
# HIGH-RISK FILES - WARNING
# =============================================================================

HIGH_RISK_PATTERNS=(
  ".tekton/*.yaml"
  ".env"
  ".env.*"
)

for pattern in "${HIGH_RISK_PATTERNS[@]}"; do
  # shellcheck disable=SC2053
  if [[ "$FILE" == $pattern ]]; then
    echo "HIGH-RISK FILE: $FILE"
    echo "   This file affects security or CI/CD."
    echo "   Changes require:"
    echo "   - Careful review"
    echo "   - Test coverage"
    echo "   - Security validation"
    echo ""
    confirm_or_exit "   Continue? (y/N)"
    break
  fi
done

# =============================================================================
# LARGE DIFFS - WARNING
# =============================================================================

if [[ -f "$FILE" ]]; then
  LINES=$(wc -l < "$FILE")
  if (( LINES > 500 )); then
    echo "LARGE FILE: $FILE ($LINES lines)"
    echo "   Prefer targeted edits over broad refactors."
    confirm_or_exit "   Continue? (y/N)"
  fi
fi

# All checks passed
exit 0
