// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	Ocm_jwtScopes = "ocm_jwt.Scopes"
)

// Defines values for ActionType.
const (
	Read  ActionType = "read"
	Write ActionType = "write"
)

// Defines values for ApprovalState.
const (
	ApprovalStateApproved    ApprovalState = "approved"
	ApprovalStateNotRequired ApprovalState = "not_required"
	ApprovalStatePending     ApprovalState = "pending"
	ApprovalStateRejected    ApprovalState = "rejected"
)

// Defines values for AuditEntryMethod.
const (
	AuditEntryMethodGET  AuditEntryMethod = "GET"
	AuditEntryMethodPOST AuditEntryMethod = "POST"
)

// Defines values for AuditListKind.
const (
	AuditListKindAuditList AuditListKind = "AuditList"
)

// Defines values for ErrorKind.
const (
	ErrorKindError ErrorKind = "Error"
)

// Defines values for ExecutionStatus.
const (
	ExecutionStatusFailed    ExecutionStatus = "failed"
	ExecutionStatusPending   ExecutionStatus = "pending"
	ExecutionStatusRunning   ExecutionStatus = "running"
	ExecutionStatusSucceeded ExecutionStatus = "succeeded"
	ExecutionStatusTimedOut  ExecutionStatus = "timed_out"
)

// Defines values for OutputStatus.
const (
	Failed   OutputStatus = "failed"
	Pending  OutputStatus = "pending"
	Uploaded OutputStatus = "uploaded"
)

// Defines values for Scope.
const (
	AwsApi  Scope = "aws-api"
	KubeApi Scope = "kube-api"
)

// Defines values for ListAuditEntriesParamsMethod.
const (
	ListAuditEntriesParamsMethodGET  ListAuditEntriesParamsMethod = "GET"
	ListAuditEntriesParamsMethodPOST ListAuditEntriesParamsMethod = "POST"
)

// Defines values for ListExecutionsParamsDryRun.
const (
	ListExecutionsParamsDryRunFalse ListExecutionsParamsDryRun = "false"
	ListExecutionsParamsDryRunTrue  ListExecutionsParamsDryRun = "true"
)

// Defines values for ListExecutionsParamsForce.
const (
	ListExecutionsParamsForceFalse ListExecutionsParamsForce = "false"
	ListExecutionsParamsForceTrue  ListExecutionsParamsForce = "true"
)

// Defines values for GetExecutionParamsInclude.
const (
	Logs       GetExecutionParamsInclude = "logs"
	Output     GetExecutionParamsInclude = "output"
	Outputlogs GetExecutionParamsInclude = "output,logs"
)

// ActionType Whether the Trusted Action is read-only or mutating
type ActionType string

// ApprovalState Approval lifecycle for an execution
type ApprovalState string

// AuditEntry defines model for AuditEntry.
type AuditEntry struct {
	// Action TA name (populated for POST /run calls; empty otherwise)
	Action *string `json:"action,omitempty"`

	// ApprovalState Approval state at time of POST (populated for POST /run calls; empty otherwise)
	ApprovalState *string `json:"approval_state,omitempty"`

	// ExecutionId Execution ID. For POST /run: the created ID. For GET /runs/{id}: the accessed ID. Empty otherwise.
	ExecutionId *string `json:"execution_id,omitempty"`

	// Id Unique audit entry ID
	Id openapi_types.UUID `json:"id"`

	// Jira Jira ticket (populated for POST /run calls; empty otherwise)
	Jira *string `json:"jira,omitempty"`

	// Method HTTP method
	Method AuditEntryMethod `json:"method"`

	// Path Full request URI (path + query parameters)
	Path string `json:"path"`

	// StatusCode HTTP response status code
	StatusCode int `json:"status_code"`

	// TargetCluster Target cluster (populated for POST /run calls; empty otherwise)
	TargetCluster *string `json:"target_cluster,omitempty"`

	// Timestamp When the API call was made (nanosecond precision)
	Timestamp time.Time `json:"timestamp"`

	// Username OCM username of caller
	Username string `json:"username"`
}

// AuditEntryMethod HTTP method
type AuditEntryMethod string

// AuditList defines model for AuditList.
type AuditList struct {
	// Items Audit log entries (sorted by timestamp descending)
	Items []AuditEntry `json:"items"`

	// Kind Always "AuditList"
	Kind AuditListKind `json:"kind"`

	// Total Total number of matching audit entries
	Total int `json:"total"`
}

// AuditListKind Always "AuditList"
type AuditListKind string

// Error defines model for Error.
type Error struct {
	// Code Machine-readable error code
	Code string `json:"code"`

	// Kind Always "Error"
	Kind ErrorKind `json:"kind"`

	// Reason Human-readable error message
	Reason string `json:"reason"`
}

// ErrorKind Always "Error"
type ErrorKind string

// Execution defines model for Execution.
type Execution struct {
	// Action Trusted Action name
	Action string `json:"action"`

	// ApprovalState Approval lifecycle for an execution
	ApprovalState *ApprovalState `json:"approval_state,omitempty"`

	// CompletedAt When the reconciler detected both Jobs done
	CompletedAt *time.Time `json:"completed_at,omitempty"`

	// CreatedAt When the execution was requested
	CreatedAt time.Time `json:"created_at"`

	// DryRun Whether this was a dry-run execution
	DryRun *bool `json:"dry_run,omitempty"`

	// DurationSeconds Total wall-clock time (completed_at - created_at) in seconds
	DurationSeconds *int `json:"duration_seconds,omitempty"`

	// Force Whether safety checks were bypassed
	Force *bool `json:"force,omitempty"`

	// Id Execution ID
	Id openapi_types.UUID `json:"id"`

	// Jira Associated Jira ticket
	Jira *string `json:"jira,omitempty"`

	// Logs Raw text content of execution.log. Only included when include=logs is set and execution is in a terminal state.
	Logs *string `json:"logs,omitempty"`

	// ManifestWorkName Dispatch resource name
	ManifestWorkName *string `json:"manifest_work_name,omitempty"`

	// Output Parsed JSON output from the TA. Only included when include=output is set and execution is in a terminal state.
	Output *interface{} `json:"output,omitempty"`

	// OutputPath URI for output artifact
	OutputPath *string `json:"output_path,omitempty"`

	// OutputStatus State of artifact upload
	OutputStatus *OutputStatus `json:"output_status,omitempty"`

	// Params Parameters passed at submission time
	Params *map[string]string `json:"params,omitempty"`

	// Revision Git SHA of TA definition
	Revision *string `json:"revision,omitempty"`

	// RunnerSeconds Runner Job wall-clock time in seconds
	RunnerSeconds *int `json:"runner_seconds,omitempty"`

	// Scope Where the Trusted Action executes (Kubernetes API or AWS API)
	Scope *Scope `json:"scope,omitempty"`

	// Status Lifecycle state of a Trusted Action execution
	Status ExecutionStatus `json:"status"`

	// TargetCluster Target cluster identifier
	TargetCluster string `json:"target_cluster"`

	// Type Whether the Trusted Action is read-only or mutating
	Type *ActionType `json:"type,omitempty"`

	// UpdatedAt Last time the execution record changed
	UpdatedAt time.Time `json:"updated_at"`

	// UploadSeconds Time from runner completion to uploader completion in seconds
	UploadSeconds *int `json:"upload_seconds,omitempty"`

	// Username OCM username of caller
	Username *string `json:"username,omitempty"`
}

// ExecutionList defines model for ExecutionList.
type ExecutionList struct {
	// HasMore Whether more results are available
	HasMore bool        `json:"has_more"`
	Items   []Execution `json:"items"`

	// Limit Max results per page
	Limit int `json:"limit"`

	// Page Current page number
	Page int `json:"page"`

	// Total Total number of matching executions
	Total int `json:"total"`
}

// ExecutionRequest defines model for ExecutionRequest.
type ExecutionRequest struct {
	// DryRun Execute the TA's dry_run_action instead (preview)
	DryRun *bool `json:"dry_run,omitempty"`

	// Force Bypass write cooldown and max-concurrent limits
	Force *bool `json:"force,omitempty"`

	// Jira Jira ticket reference; must match PROJECT-NUMBER format (e.g. ROSAENG-1234)
	Jira string `json:"jira"`

	// Params Key-value pairs of TA parameters (all values are strings)
	Params *map[string]string `json:"params,omitempty"`

	// TargetCluster Target cluster identifier
	TargetCluster string `json:"target_cluster"`
}

// ExecutionStatus Lifecycle state of a Trusted Action execution
type ExecutionStatus string

// OutputStatus State of artifact upload
type OutputStatus string

// Scope Where the Trusted Action executes (Kubernetes API or AWS API)
type Scope string

// TrustedAction defines model for TrustedAction.
type TrustedAction struct {
	// Authorization Authorization policy for this TA. The approval field is "none" (no approval needed) or a structured object defining approval requirements.
	Authorization *struct {
		// Approval Approval policy: "none" or structured approval requirements
		Approval *string `json:"approval,omitempty"`
	} `json:"authorization,omitempty"`

	// Description Human-readable description of the action
	Description string `json:"description"`

	// DryRunAction Name of a read TA to execute when dry_run is set
	DryRunAction *string `json:"dry_run_action,omitempty"`

	// Name Trusted Action name
	Name string `json:"name"`

	// Params Full parameter definitions
	Params *[]TrustedActionParam `json:"params,omitempty"`

	// Scope Where the Trusted Action executes (Kubernetes API or AWS API)
	Scope Scope `json:"scope"`

	// Type Whether the Trusted Action is read-only or mutating
	Type ActionType `json:"type"`

	// WriteCooldownSeconds Per-TA write cooldown override in seconds (0 uses global default)
	WriteCooldownSeconds *int `json:"write_cooldown_seconds,omitempty"`
}

// TrustedActionCatalog defines model for TrustedActionCatalog.
type TrustedActionCatalog struct {
	// Items Available Trusted Actions (sorted alphabetically by name)
	Items []TrustedActionSummary `json:"items"`

	// Total Total number of available Trusted Actions
	Total int `json:"total"`
}

// TrustedActionParam defines model for TrustedActionParam.
type TrustedActionParam struct {
	// Default Default value (empty string if none)
	Default *string `json:"default,omitempty"`

	// Description Human-readable parameter description
	Description *string `json:"description,omitempty"`

	// Name Parameter name
	Name string `json:"name"`

	// Required Whether the parameter is required
	Required *bool `json:"required,omitempty"`
}

// TrustedActionSummary defines model for TrustedActionSummary.
type TrustedActionSummary struct {
	// Description Human-readable description of the action
	Description string `json:"description"`

	// Name Trusted Action name
	Name string `json:"name"`

	// Scope Where the Trusted Action executes (Kubernetes API or AWS API)
	Scope Scope `json:"scope"`

	// Type Whether the Trusted Action is read-only or mutating
	Type ActionType `json:"type"`
}

// ListAuditEntriesParams defines parameters for ListAuditEntries.
type ListAuditEntriesParams struct {
	// Limit Max results per page (1-200)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Action Filter by Trusted Action name
	Action *string `form:"action,omitempty" json:"action,omitempty"`

	// Target Filter by target cluster
	Target *string `form:"target,omitempty" json:"target,omitempty"`

	// Operator Filter by operator name
	Operator *string `form:"operator,omitempty" json:"operator,omitempty"`

	// Method Filter by HTTP method
	Method *ListAuditEntriesParamsMethod `form:"method,omitempty" json:"method,omitempty"`

	// ApprovalState Filter by approval state
	ApprovalState *ApprovalState `form:"approval_state,omitempty" json:"approval_state,omitempty"`

	// Since Time filter. Accepts duration shorthand (30s, 5m, 1h, 24h, 7d) or RFC3339 timestamp.
	Since *string `form:"since,omitempty" json:"since,omitempty"`
}

// ListAuditEntriesParamsMethod defines parameters for ListAuditEntries.
type ListAuditEntriesParamsMethod string

// ListExecutionsParams defines parameters for ListExecutions.
type ListExecutionsParams struct {
	// Limit Max results per page (1-100)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Status Filter by execution status
	Status *ExecutionStatus `form:"status,omitempty" json:"status,omitempty"`

	// Action Filter by Trusted Action name (exact match)
	Action *string `form:"action,omitempty" json:"action,omitempty"`

	// Target Filter by target cluster (exact match)
	Target *string `form:"target,omitempty" json:"target,omitempty"`

	// Operator Filter by operator name (exact match)
	Operator *string `form:"operator,omitempty" json:"operator,omitempty"`

	// Scope Filter by scope
	Scope *Scope `form:"scope,omitempty" json:"scope,omitempty"`

	// Type Filter by type
	Type *ActionType `form:"type,omitempty" json:"type,omitempty"`

	// OutputStatus Filter by output status
	OutputStatus *OutputStatus `form:"output_status,omitempty" json:"output_status,omitempty"`

	// ApprovalState Filter by approval state
	ApprovalState *ApprovalState `form:"approval_state,omitempty" json:"approval_state,omitempty"`

	// DryRun Filter by dry-run flag
	DryRun *ListExecutionsParamsDryRun `form:"dry_run,omitempty" json:"dry_run,omitempty"`

	// Force Filter by force flag
	Force *ListExecutionsParamsForce `form:"force,omitempty" json:"force,omitempty"`

	// Since Time filter. Accepts duration shorthand (30s, 5m, 1h, 24h, 7d) or RFC3339 timestamp (2026-06-10T00:00:00Z).
	Since *string `form:"since,omitempty" json:"since,omitempty"`
}

// ListExecutionsParamsDryRun defines parameters for ListExecutions.
type ListExecutionsParamsDryRun string

// ListExecutionsParamsForce defines parameters for ListExecutions.
type ListExecutionsParamsForce string

// GetExecutionParams defines parameters for GetExecution.
type GetExecutionParams struct {
	// Include Opt-in content to include alongside metadata. Comma-separated combination of "output" and "logs".
	Include *GetExecutionParamsInclude `form:"include,omitempty" json:"include,omitempty"`
}

// GetExecutionParamsInclude defines parameters for GetExecution.
type GetExecutionParamsInclude string

// CreateExecutionJSONRequestBody defines body for CreateExecution for application/json ContentType.
type CreateExecutionJSONRequestBody = ExecutionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all available Trusted Actions
	// (GET /)
	Catalog(w http.ResponseWriter, r *http.Request)
	// List API call audit log entries
	// (GET /audit)
	ListAuditEntries(w http.ResponseWriter, r *http.Request, params ListAuditEntriesParams)
	// List executions
	// (GET /runs)
	ListExecutions(w http.ResponseWriter, r *http.Request, params ListExecutionsParams)
	// Retrieve execution details
	// (GET /runs/{id})
	GetExecution(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params GetExecutionParams)
	// Describe a specific Trusted Action
	// (GET /{action})
	Describe(w http.ResponseWriter, r *http.Request, action string)
	// Execute a Trusted Action
	// (POST /{action}/run)
	CreateExecution(w http.ResponseWriter, r *http.Request, action string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all available Trusted Actions
// (GET /)
func (_ Unimplemented) Catalog(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List API call audit log entries
// (GET /audit)
func (_ Unimplemented) ListAuditEntries(w http.ResponseWriter, r *http.Request, params ListAuditEntriesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List executions
// (GET /runs)
func (_ Unimplemented) ListExecutions(w http.ResponseWriter, r *http.Request, params ListExecutionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve execution details
// (GET /runs/{id})
func (_ Unimplemented) GetExecution(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params GetExecutionParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Describe a specific Trusted Action
// (GET /{action})
func (_ Unimplemented) Describe(w http.ResponseWriter, r *http.Request, action string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Execute a Trusted Action
// (POST /{action}/run)
func (_ Unimplemented) CreateExecution(w http.ResponseWriter, r *http.Request, action string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Catalog operation middleware
func (siw *ServerInterfaceWrapper) Catalog(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Catalog(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAuditEntries operation middleware
func (siw *ServerInterfaceWrapper) ListAuditEntries(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, Ocm_jwtScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAuditEntriesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "action" -------------

	err = runtime.BindQueryParameter("form", true, false, "action", r.URL.Query(), &params.Action)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		return
	}

	// ------------- Optional query parameter "target" -------------

	err = runtime.BindQueryParameter("form", true, false, "target", r.URL.Query(), &params.Target)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "target", Err: err})
		return
	}

	// ------------- Optional query parameter "operator" -------------

	err = runtime.BindQueryParameter("form", true, false, "operator", r.URL.Query(), &params.Operator)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "operator", Err: err})
		return
	}

	// ------------- Optional query parameter "method" -------------

	err = runtime.BindQueryParameter("form", true, false, "method", r.URL.Query(), &params.Method)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "method", Err: err})
		return
	}

	// ------------- Optional query parameter "approval_state" -------------

	err = runtime.BindQueryParameter("form", true, false, "approval_state", r.URL.Query(), &params.ApprovalState)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "approval_state", Err: err})
		return
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAuditEntries(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListExecutions operation middleware
func (siw *ServerInterfaceWrapper) ListExecutions(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, Ocm_jwtScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListExecutionsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "action" -------------

	err = runtime.BindQueryParameter("form", true, false, "action", r.URL.Query(), &params.Action)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		return
	}

	// ------------- Optional query parameter "target" -------------

	err = runtime.BindQueryParameter("form", true, false, "target", r.URL.Query(), &params.Target)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "target", Err: err})
		return
	}

	// ------------- Optional query parameter "operator" -------------

	err = runtime.BindQueryParameter("form", true, false, "operator", r.URL.Query(), &params.Operator)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "operator", Err: err})
		return
	}

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", r.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "scope", Err: err})
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", r.URL.Query(), &params.Type)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Optional query parameter "output_status" -------------

	err = runtime.BindQueryParameter("form", true, false, "output_status", r.URL.Query(), &params.OutputStatus)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "output_status", Err: err})
		return
	}

	// ------------- Optional query parameter "approval_state" -------------

	err = runtime.BindQueryParameter("form", true, false, "approval_state", r.URL.Query(), &params.ApprovalState)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "approval_state", Err: err})
		return
	}

	// ------------- Optional query parameter "dry_run" -------------

	err = runtime.BindQueryParameter("form", true, false, "dry_run", r.URL.Query(), &params.DryRun)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dry_run", Err: err})
		return
	}

	// ------------- Optional query parameter "force" -------------

	err = runtime.BindQueryParameter("form", true, false, "force", r.URL.Query(), &params.Force)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "force", Err: err})
		return
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListExecutions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExecution operation middleware
func (siw *ServerInterfaceWrapper) GetExecution(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, Ocm_jwtScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetExecutionParams

	// ------------- Optional query parameter "include" -------------

	err = runtime.BindQueryParameter("form", true, false, "include", r.URL.Query(), &params.Include)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExecution(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Describe operation middleware
func (siw *ServerInterfaceWrapper) Describe(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "action" -------------
	var action string

	err = runtime.BindStyledParameterWithOptions("simple", "action", chi.URLParam(r, "action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Describe(w, r, action)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateExecution operation middleware
func (siw *ServerInterfaceWrapper) CreateExecution(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "action" -------------
	var action string

	err = runtime.BindStyledParameterWithOptions("simple", "action", chi.URLParam(r, "action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, Ocm_jwtScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateExecution(w, r, action)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/", wrapper.Catalog)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/audit", wrapper.ListAuditEntries)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/runs", wrapper.ListExecutions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/runs/{id}", wrapper.GetExecution)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/{action}", wrapper.Describe)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/{action}/run", wrapper.CreateExecution)
	})

	return r
}
